import type { Metadata } from "next";
import { Geist, Geist_Mono, Chivo,Licorice} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
  weight: ["100","200","300", "400", "500","600", "700","800","900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${chivo.variable} h-full antialiased`}
    >
      {/* 1. h-full on html/body ensures the page calculates height correctly 
      */}
      <body className="min-h-full flex flex-col bg-[#297B43]"> 
        
        {/* 2. WRAPPER: This container slides OVER the footer.
               It needs 'relative', a high 'z-index', and a 'bg' color.
        */}
        <div className="relative z-10 bg-[#297B43] shadow-2xl">
          <Header />
          <main>{children}</main>
        </div>

        {/* 3. FOOTER: Sticks to the bottom and stays at z-0.
        */}
        <div className="sticky bottom-0 z-0">
          <Footer />
        </div>

      </body>
    </html>
  );
}
